version: '3'
services:
  my-sql:
    container_name: my-sql
    image: mysql:5.7
    ports:
      - 3307:33060
    environment:
      - MYSQL_ROOT_PASSWORD=isen-brief
      - MYSQL_DATABASE=covid
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
  grafana:
    image: grafana/grafana
    links:
      - my-sql
    ports:
      - 3001:3000   
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
